# Google Cloud Build 配置文件
# 用于自动化构建和部署到 Cloud Run

steps:
  # 构建 Docker 镜像
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'build-image'
    timeout: '1200s'  # 20 分钟超时（前端构建可能需要时间）

  # 推送镜像到 Container Registry (SHA 版本)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
    id: 'push-image-sha'
    waitFor: ['build-image']

  # 推送镜像到 Container Registry (latest 标签)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
    id: 'push-image-latest'
    waitFor: ['build-image']

  # 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '${_MEMORY:-1Gi}'
      - '--cpu'
      - '${_CPU:-1}'
      - '--timeout'
      - '${_TIMEOUT:-600}'
      - '--max-instances'
      - '${_MAX_INSTANCES:-10}'
      - '--min-instances'
      - '${_MIN_INSTANCES:-0}'
      - '--set-env-vars'
      - 'PORT=8080,FLASK_DEBUG=false'
    id: 'deploy-cloud-run'
    waitFor: ['push-image-sha']

# 替换变量说明：
# - ${_SERVICE_NAME}: Cloud Run 服务名称（需要在 Cloud Build 触发器中设置，例如：ais-reel）
# - ${_REGION}: 部署区域（例如：us-central1）
# - ${_MEMORY}: 内存配置（默认：1Gi）
# - ${_CPU}: CPU 配置（默认：1）
# - ${_TIMEOUT}: 请求超时（默认：600 秒）
# - ${_MAX_INSTANCES}: 最大实例数（默认：10）
# - ${_MIN_INSTANCES}: 最小实例数（默认：0）
# - $PROJECT_ID: GCP 项目 ID（自动提供）
# - $SHORT_SHA: Git commit SHA（自动提供）

# 注意：
# 1. 环境变量（如 GEMINI_API_KEY）应该在 Cloud Run 服务配置中设置，或通过 Secret Manager 引用
# 2. 如果使用 Cloud Run 的持续部署功能，通常不需要此文件
# 3. Cloud Run 会自动处理构建和部署流程

# 构建选项
options:
  machineType: 'E2_HIGHCPU_8'  # 使用高性能机器以加快构建速度
  logging: CLOUD_LOGGING_ONLY

# 超时设置
timeout: '1800s'  # 30 分钟总超时
